// Everything the guide teaches, as data. The page is a renderer over this file.

export const FEATURES = [
  {
    id: 'markets', name: 'Ten markets in one book', fn: 'WEI',
    tag: 'Markets',
    short: 'Equities from ten countries, plus crypto, bonds, indices and FX — all booked in native currency and translated to USD.',
    body: [
      'PaperTerminal covers the United States, India, Japan, South Korea, Singapore, China, Germany, the United Kingdom, France and Canada. Because those exchanges span every time zone, something is nearly always open.',
      'Each market carries its own trading hours — including the lunch breaks in Tokyo, Shanghai and Singapore — plus its own currency, settlement convention, tick size and lot size. A single Japanese lot is 100 shares, so a position there is larger than the share price suggests.',
      'Everything is booked in the currency it trades in and translated to USD at live rates. That means currency shows up as its own line in your P&L rather than hiding inside the return. Buy a Japanese stock and you own two bets: the company, and the yen.',
    ],
    points: [
      ['WEI', 'World index board and the live session clock for all ten exchanges'],
      ['DES', 'Full description of any security, including its local hours'],
      ['FXIP', 'The exchange rates every foreign position is translated at'],
    ],
    terms: ['Exchange', 'Trading session', 'Currency risk', 'Lot size', 'Settlement'],
  },
  {
    id: 'data', name: 'Where the prices come from', fn: 'SET',
    tag: 'Data',
    short: 'Free feeds, merged across providers, with the age of every price shown on screen.',
    body: [
      'No single free vendor covers all ten exchanges, so PaperTerminal asks several and merges what comes back. Each provider is queried only for the symbols still missing, and partial answers are kept rather than discarded.',
      'Crypto refreshes every 15 seconds, equities and indices every 60, FX every 5 minutes. Closed venues are polled far more slowly to protect a real request budget — the free equity tier allows 800 calls a day.',
      'Every price carries its age. Fields turn amber and then red as they go stale, and the order ticket tells you how old a quote is before you fill against it. That disclosure matters more than it sounds: filling against a twenty-minute-old print while believing it is live is a genuinely expensive mistake.',
      'If nothing answers at all, the terminal falls back to synthetic prices so every feature stays usable — and says so unmistakably, with a DEMO badge, hatched panel headers and a tag on every affected row. Those numbers are a seeded random walk, not quotes.',
    ],
    points: [
      ['SET', 'Feed status, data source, and how many requests you have spent'],
      ['DES', 'Per-security quote age and which provider answered'],
    ],
    terms: ['Stale price', 'Liquidity', 'Trading session'],
  },
  {
    id: 'trading', name: 'Orders that behave like orders', fn: 'TRAD',
    tag: 'Trading',
    short: 'Market, limit, stop, stop-limit and trailing stops — all crossing a real spread and paying real slippage.',
    body: [
      'Every fill crosses a synthetic spread scaled to how liquid the instrument is, and larger orders pay market impact on top. Buying and instantly selling loses money, exactly as it does in reality.',
      'Resting orders are checked against every incoming tick, so a stop-loss actually protects something rather than being decorative. Trailing stops ratchet up with the mark and never move back down.',
      'The order ticket deliberately shows what a broker\'s ticket hides: the spread you are crossing, the estimated slippage, the commission, the price age, what the position will cost in buying power, and the tax rate that will apply to the gain.',
    ],
    points: [
      ['TRAD', 'The order ticket — reachable from any board row or DES'],
      ['BLOT', 'Every trade, with the mid, the fill, the slippage and the price age'],
      ['ALRT', 'Resting orders and their distance from being triggered'],
    ],
    terms: ['Market order', 'Limit order', 'Stop-loss order', 'Trailing stop', 'Slippage', 'Spread'],
  },
  {
    id: 'options', name: 'Options priced by model, not by vendor', fn: 'OMON',
    tag: 'Derivatives',
    short: 'Full chains on every underlying in every market, with real Greeks and a fitted volatility skew.',
    body: [
      'There is no free listed options data outside the US. Rather than leave nine markets with dead option boards, PaperTerminal prices every chain the same way: Black-Scholes-Merton for European contracts, and a 160-step Cox-Ross-Rubinstein binomial tree for American ones, which is the only way to handle early exercise correctly.',
      'Volatility comes from each name\'s own price history, blending four estimators, plus a variance risk premium and a term structure. On top of that sits a fitted skew, so downside puts carry a higher implied volatility than upside calls — the shape a real equity board has, and the reason protection costs more than speculation.',
      'Greeks are shown in trader units: vega per volatility point, theta per calendar day. Vanna and charm are there too, because a hedge that was right on Friday can be wrong on Monday without the price moving at all.',
      'Strikes, expiries and quoted prices are generated rather than quoted. Open interest is decorative. The mathematics underneath is real.',
    ],
    points: [
      ['OMON', 'The full option board for any underlying'],
      ['OV', 'Single-contract valuation with every Greek and a payoff diagram'],
    ],
    terms: ['Option', 'Delta', 'Gamma', 'Theta', 'Vega', 'Implied volatility', 'Volatility skew', 'Black-Scholes model', 'Binomial model'],
  },
  {
    id: 'futures', name: 'Futures, forwards and bonds', fn: 'FUT',
    tag: 'Derivatives',
    short: 'Cost-of-carry pricing, daily variation margin, and sovereign bonds with genuine bond arithmetic.',
    body: [
      'Futures are priced by cost of carry, so contango and backwardation are visible and rolling costs you. They mark to market daily — cash actually moves — which is what makes futures losses bite immediately instead of accumulating quietly.',
      'Forwards are priced by covered interest parity and settle only at maturity. Nothing moves in between, which is precisely why a losing forward stays silent right up until it does not. Holding both side by side is the clearest way to feel the difference.',
      'Contracts are deliberately micro-sized so they are reachable on a four-figure account. The leverage column on the futures board shows why a small adverse move can erase the initial margin entirely.',
      'The twelve sovereign bonds are synthetic instruments, but the arithmetic is not: price from yield, clean and dirty price, accrued interest, Macaulay and modified duration, convexity and DV01.',
    ],
    points: [
      ['FUT', 'Futures board with basis, carry state and true leverage'],
      ['FRD', 'Forward curve and the rate differential driving it'],
      ['YCRV', 'Yield curves for nine currencies, and the tradeable bonds'],
    ],
    terms: ['Futures contract', 'Forward contract', 'Contango', 'Backwardation', 'Variation margin', 'Duration', 'DV01'],
  },
  {
    id: 'margin', name: 'What leverage costs while you hold it', fn: 'MARG',
    tag: 'The point',
    short: 'Reg T margin, a separate borrow facility, daily interest, and the break-even move carry forces on you.',
    body: [
      'This is the part most paper trading apps skip, and the reason this one exists. Margin follows Reg T — 50% initial, 25% FINRA maintenance floor, 30% house — with the CBOE formula for naked short options and SPAN-style requirements on futures.',
      'The borrow desk is separate from margin, and deliberately so. It is an uncollateralised loan: it will not force-liquidate you, and your balance is allowed to go negative and stay there. Rates are tiered — the more you owe, the worse your terms — over a base that tracks the live short-end yield, so when real policy rates move, your carry moves.',
      'Interest accrues every calendar day, weekends included. Debt does not observe market hours. The MARG panel turns that into two numbers that are hard to ignore: how far the book must rise just to cover carry, and how many days of runway remain before interest alone finishes the account.',
      'The pattern day trader rule is modelled too. Four day trades in five business days under $25,000 flags you and blocks opening new ones. On a small account with intraday ambitions you will hit it, and hitting it is the lesson.',
    ],
    points: [
      ['MARG', 'Margin state, cost of capital, stress table and PDT status'],
      ['BORR', 'Draw and repay, with the rate card and what a loan actually costs over time'],
    ],
    terms: ['Margin', 'Leverage', 'Maintenance margin', 'Margin call', 'Margin interest', 'Break-even on carry', 'Pattern day trader', 'Buying power'],
  },
  {
    id: 'tax', name: 'What the gain costs after you take it', fn: 'TAX',
    tag: 'The point',
    short: 'US federal tax modelled per regime, because the same $1,000 is taxed three different ways.',
    body: [
      'Sell a stock inside a year and the profit is taxed as ordinary income. Hold it past a year and the rate drops sharply. Make the same money in crypto and the split is identical — but the wash sale rule does not apply, because crypto is property rather than a security, so a loss can be harvested and the position rebought immediately.',
      'Make it in futures or broad-based index options and Section 1256 applies instead: 60% long term and 40% short term regardless of how briefly you held, plus mark-to-market at year end. You can owe real tax on a paper gain in a position you never closed.',
      'The lot method is yours to choose. FIFO sells your oldest and usually cheapest shares first, maximising the taxable gain. HIFO sells the most expensive first. The panel shows the bill under each method on your actual trades, which is the fastest way to see that the same trading can produce materially different outcomes.',
      'Margin interest appears as investment interest expense, capped at net investment income. Losses offset gains, with a $3,000 annual deduction against ordinary income and the rest carried forward.',
    ],
    points: [
      ['TAX', 'Full liability, the three regimes side by side, wash sales and lot comparison'],
    ],
    terms: ['Capital gain', 'Short-term capital gain', 'Long-term capital gain', 'Wash sale', 'Section 1256 contract', '60/40 rule', 'FIFO', 'HIFO', 'Property treatment'],
  },
  {
    id: 'risk', name: 'What you are actually exposed to', fn: 'RISK',
    tag: 'Analytics',
    short: 'Volatility decomposition, VaR, second-order stress tests and per-trade statistics.',
    body: [
      'Portfolio volatility is decomposed by position using a correlation model that clusters by market and sector, so six correlated names stop reading as diversification. The panel flags when a single position carries a disproportionate share of the risk — often not the largest holding, but the most volatile one.',
      'Options are stressed to second order: delta plus half gamma squared. This is why a short option book looks harmless at −2% and ruinous at −20%. Gamma is not linear and neither is the damage.',
      'Trade statistics answer the only question that settles a strategy: expectancy. Win rate alone is nearly meaningless — 90% winners with one catastrophic loss is a losing system, and 30% winners with large gains can be an excellent one.',
    ],
    points: [
      ['RISK', 'Exposure, VaR, expected shortfall, risk contributions, stress table'],
      ['PNL', 'Equity curve, drawdown, Sharpe, Sortino, Calmar and trade statistics'],
    ],
    terms: ['Volatility', 'Value at risk', 'Expected shortfall', 'Maximum drawdown', 'Sharpe ratio', 'Expectancy', 'Concentration risk', 'Stress test'],
  },
  {
    id: 'clock', name: 'Time passes while you are away', fn: 'PORT',
    tag: 'The point',
    short: 'Interest, weekly deposits, coupons and expiry all replay deterministically when you reopen.',
    body: [
      'You start with $1,000 and receive $1,000 every Monday. Both are configurable.',
      'Rather than run a background process, the account records the last day it processed and replays the gap when you open it, day by day, in a fixed order. Interest accrues, deposits land, coupons pay, options expire and get assigned.',
      'The same starting state always produces the same result. Close the terminal for a month, come back, and you will see exactly what thirty nights of carry did to a leveraged position — which is the single hardest thing to feel in a simulator that pauses when you stop looking.',
    ],
    points: [
      ['PORT', 'Positions, working orders and the account summary'],
      ['MARG', 'Accrued interest not yet charged'],
    ],
    terms: ['Margin interest', 'Assignment', 'Expiration', 'Coupon'],
  },
  {
    id: 'charts', name: 'Real charts, one click away', fn: 'CHRT',
    tag: 'Markets',
    short: 'Every security links out to TradingView and other platforms for candles, indicators and drawing tools.',
    body: [
      'PaperTerminal draws daily closes, which is enough to judge a trend and not much else. Rather than half-build a charting package, every security links out to the platforms people already use.',
      'TradingView comes first, with Yahoo Finance for fundamentals and filings, Investing.com for international coverage, NSE India for Indian names, and CoinGecko or Binance for coins.',
      'Symbol mapping is the entire difficulty — no two vendors spell the same company the same way. CHRT shows you the mapping for any security.',
    ],
    points: [
      ['CHRT', 'Every external chart for a security, plus the symbol mapping'],
      ['DES', 'VIEW CHART button on any security description'],
    ],
    terms: ['Ticker symbol', 'Types of charts', 'Time frame'],
  },
  {
    id: 'privacy', name: 'Your account, your machine', fn: 'SET',
    tag: 'Data',
    short: 'No login, no accounts, no server-side state. Export it as JSON whenever you like.',
    body: [
      'The server proxies market data and does nothing else. It has no concept of a user and holds no account state, which is why it fits in one readable file.',
      'Your account lives in your browser\'s local storage. SET exports it as JSON so you can commit it to your own repository, diff it, or delete it.',
      'Because the engine runs entirely in the browser, it also works with no server at all — on GitHub Pages, crypto and FX stay genuinely live while equities come from a committed snapshot.',
    ],
    points: [
      ['SET', 'Export, import, reset, and every configurable rule'],
    ],
    terms: [],
  },
];

export const RECIPES = [
  {
    id: 'buy-stock', name: 'Buy a stock', level: 'Start here', tag: 'Cash',
    intro: 'The simplest trade in the terminal, and the one every other recipe builds on.',
    steps: [
      ['Load the security', 'Type <code>AAPL</code> and press <kbd>GO</kbd>. For a foreign name, the ticker alone still works: <code>RELIANCE</code>, <code>7203</code>, <code>SAP</code>.'],
      ['Read the page', 'DES shows the price, the session state, and the realised and implied volatility. Check the quote age — if the venue is closed you are looking at the last print, not a live price.'],
      ['Open the ticket', 'Press <b>BUY</b>. The ticket opens with a default size scaled to your balance.'],
      ['Check what it costs', 'The ticket shows the reference mid, your estimated fill, the spread you are crossing, slippage, commission, and the cash impact. The gap between mid and fill is what immediacy costs.'],
      ['Look at the capital line', 'It tells you the initial requirement and what your buying power will be afterwards. If it would be negative, you are about to over-extend.'],
      ['Submit', 'The fill appears in <code>PORT</code> immediately, and in <code>BLOT</code> with the price age it filled against.'],
    ],
    watch: 'Buying and instantly selling loses money. That is the spread, and it is the most reliable cost in trading.',
    terms: ['Market order', 'Spread', 'Slippage', 'Buying power'],
  },
  {
    id: 'stop', name: 'Protect a position with a stop', level: 'Start here', tag: 'Risk',
    intro: 'A stop is how you decide your maximum loss in advance, while you are still calm.',
    steps: [
      ['Open your portfolio', 'Type <code>PORT</code> and press <kbd>GO</kbd>.'],
      ['Find the position', 'Press <b>STOP</b> on its row.'],
      ['Choose a distance', 'A fixed stop sits at a set price. A trailing stop follows the mark upward and never moves back down, locking in gains as they come.'],
      ['Size the distance to the volatility', 'DES shows the 1σ daily move. A stop closer than that will be triggered by ordinary noise rather than by anything meaningful.'],
      ['Place it', 'It appears in <code>ALRT</code> with its live distance from being triggered. Every incoming tick is checked against it.'],
    ],
    watch: 'A stop is not a guaranteed price. Once triggered it becomes a market order and fills wherever the market is — if the price gaps straight through it overnight, you fill on the other side.',
    terms: ['Stop-loss order', 'Trailing stop', 'Gap', 'Volatility'],
  },
  {
    id: 'short', name: 'Sell short', level: 'Intermediate', tag: 'Margin',
    intro: 'Profiting from a fall, with an asymmetry that deserves respect.',
    steps: [
      ['Load the security and open the ticket', 'Press <b>SELL</b> with no position open.'],
      ['Read the requirement', 'Shorting needs margin, and the requirement is higher than for a long. The ticket shows it.'],
      ['Submit', 'Your position shows a negative quantity in <code>PORT</code>.'],
      ['Watch the maintenance line', 'Open <code>MARG</code>. A rising price increases your requirement while reducing your equity — the two move against you together.'],
    ],
    watch: 'Maximum gain is 100%, because the price can only fall to zero. Maximum loss is unbounded, because there is no ceiling. A stop matters far more here than on a long.',
    terms: ['Short selling', 'Short squeeze', 'Maintenance margin', 'Margin call'],
  },
  {
    id: 'buy-call', name: 'Buy a call option', level: 'Intermediate', tag: 'Options',
    intro: 'A leveraged directional bet with a known maximum loss and a deadline.',
    steps: [
      ['Open the option board', 'Type <code>AAPL OMON</code> and press <kbd>GO</kbd>.'],
      ['Pick an expiry', 'The tabs show days remaining. Short-dated options are cheaper and decay faster.'],
      ['Read the header', 'It gives the ATM implied volatility and the expected 1σ move by expiry. If your target is beyond that move, you are betting against the market\'s own estimate.'],
      ['Choose a strike', 'Calls are on the left, puts on the right, strikes down the middle. Delta doubles as a rough probability of finishing in the money.'],
      ['Value it properly first', 'Press <b>BUY</b> on the strike, or open <code>OV</code> for the full breakdown — intrinsic versus time value, every Greek, and a payoff diagram.'],
      ['Submit', 'Remember the multiplier: one contract is 100 shares, so a premium of 2.50 costs 250.'],
    ],
    watch: 'Theta works against you every single day. An out-of-the-money option held to expiry is usually worth nothing — being right about direction but late is the same as being wrong.',
    terms: ['Call option', 'Strike price', 'Delta', 'Theta', 'Time value', 'Implied volatility', 'Contract multiplier'],
  },
  {
    id: 'sell-put', name: 'Sell a put', level: 'Advanced', tag: 'Options',
    intro: 'Collecting premium in exchange for an obligation you cannot cancel.',
    steps: [
      ['Open the board', '<code>SPX OMON</code>, or any underlying you would genuinely be willing to own.'],
      ['Pick a strike below the price', 'Out-of-the-money puts have no intrinsic value — the entire premium is time value, and time value decays in your favour when short.'],
      ['Press BUY on the put, then switch the ticket to SELL', 'The ticket recalculates for the short side.'],
      ['Look hard at the requirement', 'A naked short option carries a large margin requirement, calculated from the underlying value rather than the premium. On an index it can be enormous.'],
      ['Monitor it', '<code>MARG</code> shows the maintenance requirement, and <code>RISK</code> stresses it to second order.'],
    ],
    watch: 'You are paid a small premium to accept a large, sudden risk. Get assigned and you must buy the underlying at the strike no matter how far below it the price has fallen. This is the fastest way to destroy a small account.',
    terms: ['Put option', 'Naked option', 'Assignment', 'Maintenance margin', 'Gamma'],
  },
  {
    id: 'futures', name: 'Trade a future', level: 'Advanced', tag: 'Derivatives',
    intro: 'Large exposure on a small deposit, settled in cash every single day.',
    steps: [
      ['Open the board', 'Type <code>FUT</code> and press <kbd>GO</kbd>.'],
      ['Read the leverage column', 'It shows notional divided by initial margin. That number, not the margin, is your real exposure.'],
      ['Check the carry state', 'Contango means a long position bleeds a little on each roll; backwardation means it gains.'],
      ['Go LONG or SHORT', 'One contract at a time until the size makes sense to you.'],
      ['Come back tomorrow', 'Variation margin settles daily in real cash. Losses are debited whether or not you close.'],
    ],
    watch: 'A contract requiring $1,200 of margin might control $60,000 of index. A 2% adverse move erases the entire deposit.',
    terms: ['Futures contract', 'Initial margin', 'Variation margin', 'Notional value', 'Contango', 'Roll'],
  },
  {
    id: 'forward', name: 'Trade a forward', level: 'Advanced', tag: 'Derivatives',
    intro: 'The same economics as a future, with a completely different rhythm.',
    steps: [
      ['Open the pricer', 'Type <code>EURUSD FRD</code> and press <kbd>GO</kbd>.'],
      ['Read the curve', 'The forward is spot adjusted for the interest rate difference between the two currencies — covered interest parity, nothing more.'],
      ['Take a side', 'LONG or SHORT at any maturity on the ladder.'],
      ['Notice what does not happen', 'No daily settlement. No variation margin. Nothing moves until maturity.'],
    ],
    watch: 'A future tells you every day how wrong you are. A forward tells you once, at the end. That silence is the entire risk.',
    terms: ['Forward contract', 'Covered interest parity', 'Interest rate differential', 'Counterparty risk'],
  },
  {
    id: 'borrow', name: 'Borrow to trade', level: 'Advanced', tag: 'Margin',
    intro: 'The feature this whole terminal was built around.',
    steps: [
      ['Open the desk', 'Type <code>BORR</code> and press <kbd>GO</kbd>.'],
      ['Read the rate card', 'Rates are tiered — the more you owe, the worse your terms. The base tracks the live short-end yield.'],
      ['Look at the cost table first', 'It shows what borrowing $1,000 costs over a week, a month, a year and three years, and the move you need just to break even on it.'],
      ['Draw an amount', 'Cash rises. Equity does not — you now owe what you hold. That distinction is the whole lesson.'],
      ['Deploy it, then watch MARG', 'Interest per day, break-even on carry, distance to a margin call in both percent and σ, and your runway before interest alone finishes the account.'],
      ['Leave it a while', 'Close the terminal and come back later. The clock replays every day you were away, with interest accruing the entire time.'],
    ],
    watch: 'Your balance is allowed to go negative and stay there. Nothing stops you. Interest accrues every calendar day, weekends included, whether you are right or wrong.',
    terms: ['Debit balance', 'Margin interest', 'Break-even on carry', 'Leverage', 'Margin call', 'Buying power'],
  },
  {
    id: 'tax-plan', name: 'See what tax does to a gain', level: 'Intermediate', tag: 'Tax',
    intro: 'The difference between a good trade and a good outcome.',
    steps: [
      ['Make some trades and close them', 'Realised gains are what get taxed. Unrealised ones do not.'],
      ['Open the tax centre', 'Type <code>TAX</code> and press <kbd>GO</kbd>.'],
      ['Read the three-regime table', 'The same $1,000 is taxed differently depending on whether it came from a stock held under a year, a stock held over a year, crypto, or a futures contract.'],
      ['Compare lot methods', 'The panel computes your bill under FIFO, HIFO and LIFO on your actual trades. Switch method and the number moves.'],
      ['Check for wash sales', 'If you sold at a loss and rebought within thirty days, the loss was disallowed and rolled into your cost basis. Crypto is exempt — it is not a security.'],
    ],
    watch: 'Holding one more day can move a gain from ordinary income rates to long-term capital gains. On a large gain that is more than a fifth of the profit, for doing nothing.',
    terms: ['Short-term capital gain', 'Long-term capital gain', 'Wash sale', 'FIFO', 'HIFO', 'Section 1256 contract'],
  },
];

export const FUNCTIONS = [
  ['DES', 'Security description', 'Price, session, fundamentals, volatility, your position, external charts.', 'yes'],
  ['GP', 'Price graph', 'Daily closes with period statistics. Range buttons for 30 to 365 days.', 'yes'],
  ['GIP', 'Intraday graph', 'Built from ticks observed while the terminal is open.', 'yes'],
  ['CHRT', 'External charts', 'TradingView and other platforms, plus the symbol mapping.', 'yes'],
  ['OMON', 'Option monitor', 'Full chain with Greeks, implied volatility and a fitted skew.', 'yes'],
  ['OV', 'Option valuation', 'One contract in detail — Greeks, probabilities, payoff diagram.', 'yes'],
  ['FUT', 'Futures board', 'Basis, carry state, contract specs and true leverage.', 'no'],
  ['FRD', 'Forward pricer', 'Forward curve by covered interest parity.', 'yes'],
  ['PORT', 'Portfolio', 'Positions, working orders, account summary, margin warnings.', 'no'],
  ['BLOT', 'Blotter', 'Every trade with mid, fill, slippage and price age.', 'no'],
  ['PNL', 'Profit and loss', 'Equity curve, attribution, drawdown and trade statistics.', 'no'],
  ['ALRT', 'Alerts and stops', 'Resting orders and their live distance from triggering.', 'no'],
  ['MARG', 'Margin and cost of capital', 'Margin state, carry, break-even, stress table, PDT status.', 'no'],
  ['BORR', 'Borrow desk', 'Draw and repay, rate card, and what a loan really costs.', 'no'],
  ['TAX', 'Tax centre', 'Liability by regime, wash sales, lot method comparison.', 'no'],
  ['RISK', 'Risk dashboard', 'Exposure, VaR, risk contributions, second-order stress tests.', 'no'],
  ['WEI', 'World equity indices', 'Benchmark board and live exchange sessions.', 'no'],
  ['CRYP', 'Crypto monitor', 'Top 25 by market cap.', 'no'],
  ['FXIP', 'FX rates', 'Fifteen pairs with pip moves.', 'no'],
  ['YCRV', 'Yield curves and bonds', 'Nine sovereign curves and twelve tradeable bonds.', 'no'],
  ['W', 'Watchlist', 'Your saved instruments — and what the feed keeps fresh.', 'no'],
  ['MOST', 'Most active', 'Biggest movers across markets.', 'no'],
  ['SET', 'Settings', 'Capital, leverage and tax rules, plus export and import.', 'no'],
  ['HELP', 'Function index', 'The full list, inside the terminal.', 'no'],
];

// Hotspots on the annotated terminal replica.
export const ANNOTATIONS = [
  { n: 1, at: 'cmd', title: 'The command line',
    text: 'Type a ticker, a function code, or both. <code>AAPL</code> loads a security. <code>AAPL OMON</code> loads it straight into the option board. <code>PORT 3</code> sends the portfolio to panel three. Press <kbd>GO</kbd> or Return to execute.' },
  { n: 2, at: 'fkeys', title: 'Function keys',
    text: 'The blue strip maps <kbd>F1</kbd> to <kbd>F8</kbd> to the eight functions you reach for most. They inherit whatever security the focused panel is showing, so <kbd>F3</kbd> jumps straight from a stock to its options.' },
  { n: 3, at: 'panel', title: 'Four independent panels',
    text: 'Each one is separately addressable, so you can watch an option board while margin updates beside it. Press <kbd>1</kbd> to <kbd>4</kbd> to focus one when the command line is empty.' },
  { n: 4, at: 'age', title: 'Every price shows its age',
    text: 'The AGE column and the SRC column tell you how stale a quote is and which provider answered. Fields go amber and then red as they age. This is the disclosure most trading simulators leave out.' },
  { n: 5, at: 'session', title: 'Live exchange sessions',
    text: 'OPEN, CLOSED, PRE or WEEKEND for every venue, in its own local time. Ten markets across every time zone means something is nearly always trading.' },
  { n: 6, at: 'status', title: 'The status bar',
    text: 'Account equity, cash, P&L, buying power and margin used, always visible. On the right, feed health and the age of the oldest price on screen.' },
  { n: 7, at: 'tape', title: 'The ticker tape',
    text: 'Benchmark indices, major crypto and FX, scrolling continuously so you keep a peripheral sense of the market while working on something else.' },
];
